language: node_js
node_js:
  - "5.5.0"
addons:
  code_climate:
    repo_token: 423c3c1cab35bd53858eeebc2974a572e2393a59fd3bd4902a643430dee573ea
install:  npm install
script:   ./node_modules/.bin/gulp ci
after_script:
  - codeclimate-test-reporter < ./public/build/coverage/lcov.info